
DROP TABLE IF EXISTS CLIENT, COMMANDE, DETAIL, PRODUIT ;

CREATE TABLE CLIENT (
     RefC INT NOT NULL,
     NomC VARCHAR(20) NOT NULL,
     Ville VARCHAR(20) NOT NULL,
     CAT VARCHAR(2),
     PRIMARY KEY (RefC)
) ;

CREATE TABLE COMMANDE(
     RefCom INT NOT NULL,
     RefC INT NOT NULL,
     DateCom DATE NOT NULL,
     PRIMARY KEY (RefCom)
) ;

CREATE TABLE DETAIL(
    RefCOM INT NOT NULL,
    RefP  VARCHAR(5) NOT NULL,  
    Quantite INT NOT NULL,
    PRIMARY KEY (RefCOM,RefP)
) ;

CREATE TABLE PRODUIT(
    RefP   VARCHAR(5) NOT NULL,
    TypeP  VARCHAR(20)  NOT NULL,
    Prix FLOAT(6,2)  NOT NULL,
    QStock INT,
    PRIMARY KEY (RefP)
) ;


LOAD DATA LOCAL INFILE 'client.dat' INTO TABLE CLIENT ;
LOAD DATA LOCAL INFILE 'commande.dat' INTO TABLE COMMANDE ;
LOAD DATA LOCAL INFILE 'detail.dat' INTO TABLE DETAIL ;
LOAD DATA LOCAL INFILE 'produit.dat' INTO TABLE PRODUIT ;

